image:
  repository: defendersd/defender.job-scheduler
  tag: 20260718-221
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-job-scheduler
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  http:
    enabled: true
  cron:
    enabled: true
