image:
  repository: defendersd/defender.portal
  tag: 20260711-182
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-portal
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  http:
    enabled: true
