image:
  repository: defendersd/defender.identity
  tag: sha-1cc8683
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-identity
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  http:
    enabled: true
