image:
  repository: defendersd/defender.portal
  tag: b2038d8e8123473f6f2ecc2d7f2b6d5ca97f13d5
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-portal
      paths:
        - path: /
          pathType: Prefix
