image:
  repository: defendersd/defender.health-care
  tag: 20260621-116
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-health-care
      paths:
        - path: /
          pathType: Prefix
