image:
  repository: defendersd/defender.portal
  tag: d8fdd04e108c5954a3d5126c4d09172121a5c726
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: argo-portal
      paths:
        - path: /
          pathType: Prefix
autoscaling:
  http:
    enabled: true
