global:
  environment: dev

kube-prometheus-stack:
  crds:
    enabled: true
  prometheusOperator:
    tls:
      enabled: false
    admissionWebhooks:
      enabled: false
      patch:
        enabled: false
  kubeApiServer:
    enabled: false
  kubeControllerManager:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubelet:
    enabled: false
  coreDns:
    enabled: false
  grafana:
    enabled: true
    adminPassword: admin
    defaultDashboardsTimezone: utc
    sidecar:
      datasources:
        uid: P000000001
    additionalDataSources:
      - name: Loki
        uid: L000000001
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
        jsonData:
          maxLines: 1000
  prometheus:
    prometheusSpec:
      retention: 7d
      scrapeInterval: 30s
  alertmanager:
    enabled: true
  kube-state-metrics:
    enabled: true
  nodeExporter:
    enabled: true

loki:
  enabled: true
  fullnameOverride: loki
  isDefault: false
  loki:
    auth_enabled: false
    containerSecurityContext:
      readOnlyRootFilesystem: false
    commonConfig:
      path_prefix: /tmp/loki
      replication_factor: 1
    storage:
      type: filesystem
      filesystem:
        chunks_directory: /tmp/loki/chunks
        rules_directory: /tmp/loki/rules
        admin_api_directory: /tmp/loki/admin
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
    useTestSchema: true
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  singleBinary:
    replicas: 1
    persistence:
      enabled: false
  deploymentMode: SingleBinary
  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0
  monitoring:
    selfMonitoring:
      enabled: false
    serviceMonitor:
      enabled: true
  test:
    enabled: false
  lokiCanary:
    enabled: false

promtail:
  enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    snippets:
      pipelineStages:
        - cri: {}
