global:
  environment: prod

kube-prometheus-stack:
  kube-state-metrics:
    enabled: false
  nodeExporter:
    enabled: false
  alertmanager:
    enabled: false
  grafana:
    adminPassword: change-me-in-prod
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - argo-grafana
    grafana.ini:
      server:
        domain: argo-grafana
        root_url: "%(protocol)s://%(domain)s/"
      security:
        csrf_trusted_origins: "http://argo-grafana,https://argo-grafana"
  prometheus:
    prometheusSpec:
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi

loki:
  loki:
    limits_config:
      retention_period: 336h
    compactor:
      retention_enabled: true
      delete_request_store: filesystem
    commonConfig:
      path_prefix: /var/loki
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
        admin_api_directory: /var/loki/admin
  singleBinary:
    persistence:
      enabled: true
      size: 100Gi

promtail:
  tolerations: []
