global:
  environment: prod

kube-prometheus-stack:
  kube-state-metrics:
    enabled: false
  nodeExporter:
    enabled: false
  alertmanager:
    enabled: false
  grafana:
    adminPassword: change-me-in-prod
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - argo-grafana
  prometheus:
    prometheusSpec:
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 50Gi
  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi

loki:
  loki:
    commonConfig:
      path_prefix: /var/loki
    storage:
      filesystem:
        chunks_directory: /var/loki/chunks
        rules_directory: /var/loki/rules
        admin_api_directory: /var/loki/admin
  singleBinary:
    persistence:
      enabled: true
      size: 100Gi

promtail:
  tolerations: []
