{{- $autoscaling := .Values.autoscaling | default dict }}
{{- $httpAutoscaling := $autoscaling.http | default dict }}
{{- $cronAutoscaling := $autoscaling.cron | default dict }}
{{- $httpEnabled := $httpAutoscaling.enabled | default false }}
{{- $cronEnabled := $cronAutoscaling.enabled | default false }}
{{- if or $httpEnabled $cronEnabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}
  minReplicaCount: {{ $autoscaling.minReplicaCount | default 0 }}
  maxReplicaCount: {{ $autoscaling.maxReplicaCount | default 1 }}
  cooldownPeriod: {{ $autoscaling.cooldownPeriod | default 1200 }}
  triggers:
{{- if $httpEnabled }}
    - type: external-push
      metadata:
        scalerAddress: {{ $httpAutoscaling.scalerAddress | default "keda-add-ons-http-external-scaler.keda:9090" | quote }}
        interceptorRoute: {{ .Release.Name | quote }}
{{- end }}
{{- if $cronEnabled }}
    - type: cron
      metadata:
        timezone: {{ $cronAutoscaling.timezone | default "Europe/Warsaw" | quote }}
        start: {{ $cronAutoscaling.start | default "0,30 * * * *" | quote }}
        end: {{ $cronAutoscaling.end | default "10,40 * * * *" | quote }}
        desiredReplicas: {{ $cronAutoscaling.desiredReplicas | default "1" | quote }}
{{- end }}
{{- end }}
