apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: defender
    app.kubernetes.io/instance: observability-dev
spec:
  project: observability
  source:
    repoURL: https://github.com/SelDanilEv/Defender.MonoRepo.git
    targetRevision: main
    path: helm/observability
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: defender-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
